name: WebP Converter
on:
  push: 
    branches:
      - master
      - dev
    paths:
      - assets/images/*.*

jobs:
  webp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          pip install webp-converter
          webpc --r
 
